### ISSUE TITLE
User config not loaded

### ISSUE THREAD

**Issue by NetAdmin-GITAM** [sbehuret/roundcube-plugin-user-config#1]
Tested and it's not working, can you please explain step by step procedure. I want to configure $config['max_recipients'] option in roundcube per user.

**Comment by NetAdmin-GITAM** [comment]
My configuration:
user_config plugin 'config.inc.php' contains:
$config['user_config_includes'] = array(
    'abc' => 'abc_user_config.inc.php',
    'xyz' => 'xyz_user_config.inc.php',
);

In global config directory two files abc_user_config.inc.php and xyz_user_config.inc.php

abc_user_config.inc.php contains:
///<?php
$config['max_recipients'] = 2;

xyz_user_config.inc.php contains
///<?php
$config['max_recipients'] = 5;

defaults.inc.php contains:
$config['max_recipients'] = 1;

User abc can send mail to only one recipient but not 2 as configured
User xyz can send mail to only one recipient but not 5 as configured

**Comment by njsrinivas** [comment]
<?php
$config = array();
$config['max_recipients'] = 2;

xyz_user_config.inc.php contains:
<?php
$config = array();
$config['max_recipients'] = 5;

**Comment by njsrinivas** [comment]
<?php
$config['max_recipients'] = 2;

xyz_user_config.inc.php contains
<?php
$config['max_recipients'] = 5;

defaults.inc.php contains:
$config['max_recipients'] = 1;

**Comment by sbehuret** [comment]
Hi, your configuration seems fine. Did you extract/clone the plugin in {roundcube_base}/plugins/user_config? The plugin should also be enabled in {roundcube_base}/config/config.inc.php by adding 'user_config' to $config['plugins'] array. Make sure that 'abc' and 'xyz' are the actual usernames as used by roundcube internally. In case of doubt you can try logging in with 'abc' and 'abc@domain.tld' if this is applicable to your setup. If nothing works, I’d suggest you add a few php lines (e.g. exit(‘successfully loaded’);) to abc_user_config.inc.php and xyz_user_config.inc.php to check whether they are actually loaded. If these files are loaded and your settings are not taken into account, then the plugin might be loaded too late (e.g. after your specific settings are read by roundcube). Try moving 'user_config' to the left in $config['plugins'] array to load it earlier, otherwise a hack will be needed to patch your settings after roundcube has loaded them.

**Comment by NetAdmin-GITAM** [comment]
Hi, I extracted the plugin in right path "/var/www/html/rcmail/plugins/user_config" and enabled in 
"/var/www/html/rcmail/config/config.inc.php"
roundcube 'config.inc.php' contains:
$config['plugins'] = array(
	'user_config',
…..
…..	
	'filters',
);

I am using roundcube v1.2.2

I tried everything you said but still not working. Can you explain me how to confirm if user config file is loaded.

**Comment by sbehuret** [comment]
I haven't tested the plugin for your version but it's working fine with roundcube 1.3.9.
To confirm that user config is loaded, add:
exit(‘successfully loaded’);
to your user config files (abc_user_config.inc.php, xyz_user_config.inc.php).
If you see the message ‘successfully loaded’ in roundcube after logging in with the corresponding usernames, it means that your custom user config has been loaded.

**Comment by NetAdmin-GITAM** [comment]
Hi. tested with roundcube v1.3.9 also but not works. Also added 'exit(‘successfully loaded’);' in abc_user_config.inc.php file.
abc_user_config.inc.php contains:
//<?php
$config['max_recipients'] = 2;
exit(‘successfully loaded’);

**Comment by NetAdmin-GITAM** [comment]
There is no ‘successfully loaded’ message appears after login both with abc and abc@domain.com user ID's.

**Comment by NetAdmin-GITAM** [comment]
Hi. how to troubleshoot the issue.

**Comment by sbehuret** [comment]
Hi, I don’t think it’s an issue with the plugin but rather a problem with your roundcube configuration.
If you didn’t see the ‘successfully loaded‘ message, your user-specific configuration was not loaded by roundcube. It could either mean that the plugin is not properly enabled, or that the usernames you’re using in $config['user_config_includes'] are incorrect. To check how roundcube stores your usernames, you can look into the database directly or add the following statement in {roundcube_base}/plugins/user_config/user_config.php at line 34:

exit($username);

If the plugin is loaded and you're logged in, it will print the actual username that is stored in roundcube database. This is the username that will be matched against $config['user_config_includes'] array keys.
